config/routes.rb
BlueBooks::Application.routes.draw do
  
  devise_for :members

  resources :send_documents

  get "books/index"

  get "books/new"

  get "books/create"

  get "books/destroy"

  root :to => 'members#admin_home_page'

  match 'groups/edit_members_in_group/:id' => "groups#edit_members_in_group", :as => 'edit_members_in_group'
  match 'groups/showMembersInGroup/:id' => "groups#showMembersInGroup", :as => 'showMembersInGroup'
  resources :groups

  match 'schools/show_members_in_school/:id' => "schools#show_members_in_school", :as => 'show_members_in_school'
  resources :schools
  
  put 'members/remove_member_from_group/:id' => "members#remove_member_from_group", :as => 'remove_member_from_group'
  post 'members/create_new_member' => "members#create_new_member", :as => 'create_new_member'
  match 'members/admin_home_page' => "members#admin_home_page"
  resources :members
  get 'search' => "members#search"
  
  
  resources :request_accesses
  
  get 'books/update_post_approval/:id' => 'books#update_post_approval', :as => 'update_post_approval'
  put 'books/update_post_approval/:id' => 'books#update_post_approval', :as => 'update_post_approval'
  get 'books/update/:id' => 'books#update', :as => 'update'
  match 'books/showBook_pdf/:id' => 'books#showBook_pdf', :as => 'showBook_pdf'
  resources :books, only: [:index, :new, :create, :destroy]
  get 'book_search' => "books#book_search"  
  match '/download_book/:id' => 'books#download_book', :as => 'download_book'
  
  

end

app/models/group.rb
# == Schema Information
#
# Table name: groups
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Group < ActiveRecord::Base
  attr_accessible :name, :id
  #has_many :email_addresses
  has_many :members
  validates_uniqueness_of :name
  validates :name, presence: {message: ' cannot be empty'}
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @groups }
    end
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
    @group = Group.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @group }
    end
  end

  # GET /groups/new
  # GET /groups/new.json
  def new
    @group = Group.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @group }
    end
  end

  # GET /groups/1/edit
  def edit
    @group = Group.find(params[:id])
    
    redirect_to edit_members_in_group_path
  end

  def edit_members_in_group
    @current_group = Group.find(params[:id])
    @members_in_group = @current_group.members
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(params[:group])

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render json: @group, status: :created, location: @group }
      else
        format.html { render action: "new" }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /groups/1
  # PUT /groups/1.json
  # def update
  #   @group = Group.find(params[:id])

  #   respond_to do |format|
  #     if @group.update_attributes(params[:group])
  #       format.html { redirect_to @group, notice: 'Group was successfully updated.' }
  #       format.json { head :no_content }
  #     else
  #       format.html { render action: "edit" }
  #       format.json { render json: @group.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group = Group.find(params[:id])
    @group.destroy

    respond_to do |format|
      format.html { redirect_to groups_url }
      format.json { head :no_content }
    end
  end

  def showMembersInGroup
    @group = Group.find(params[:id])

    @membersInGroup = @group.members
    
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this email_group from being saved:</h2>

      <ul>
      <% @group.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<%= form_for @group, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                groups_path, :class => 'btn' %>
  </div>
<% end %>

app/views/groups/_navBar.html.erb
  <div class="col-xs-3">
    
  </div>
  <div class="col-xs-9">
    <div class="navbar navbar-default navbar-inverse">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          
          <div class="nav-collapse">
            <ul class="nav">
              <li><%= link_to "Home",members_admin_home_page_path %></li>
              <li><%= link_to "Books", books_path %></li>
              <li><%= link_to "Members", members_path if(current_member.group and current_member.group.name.downcase.eql?"admin")%></li>
              <li><%= link_to "Schools", schools_path if(current_member.group and current_member.group.name.downcase.eql?"admin")%></li>
              
              <li><%= link_to "Request Access", new_request_access_path if(current_member.group.nil? or !current_member.group.name.downcase.eql?"admin")%></li>
            </ul>
          </div>
        </div>
      </div>
    </div>

app/views/groups/edit.html.erb
<%- model_class = Group -%>
	<%= render :partial => 'navBar' %>
	<h4><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h4>

	<%= render :partial => 'form' %>
	</div>
</div>

app/views/groups/edit_members_in_group.html.erb
<%- model_class = Group -%>
  <%= render :partial => 'navBar' %>
  <h4><%= "Group: #{@current_group.name}" %></h4>
  <table class="table table-striped">
  <thead>
      <tr>
        <th><%= model_class.human_attribute_name(:first_name) %></th>
        <th><%= model_class.human_attribute_name(:last_name) %></th>
        <th><%= model_class.human_attribute_name(:pennkey) %></th>
        <th><%= model_class.human_attribute_name(:email_address) %></th>
        <th><%= model_class.human_attribute_name(:school_id) %></th>
      </tr>
    </thead>
  <tbody>
    <% unless @members_in_group.nil? %>
    <% @members_in_group.each do |member| %>
      <tr>
        <td><%= member.first_name %></td>
        <td><%= member.last_name %></td>
        <td><%= member.pennkey %></td>
        <td><%= member.email_address %></td>
        <td><%= member.school.name %></td>
        <td>
          <%= link_to "Remove", remove_member_from_group_path(member),:class => 'btn', :method => :put unless @current_group.name.downcase.eql?"admin"%></td>
      </tr>
    <% end %>
    <% end %>
  </tbody>
</table>
  <%= link_to t('.back', :default => t("helpers.links.back")), groups_path, :class => 'btn'  %>

  </div>
</div>

app/views/groups/index.html.erb
<%- model_class = Group -%>
    <%= render :partial => 'navBar' %>
    <h4><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h4>
    <%= link_to t('.new', :default => t("helpers.links.new")),new_group_path,:class => 'btn btn-primary' %>
    <%= link_to "Back", members_admin_home_page_path, :class => 'btn btn-default' %>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% unless @groups.nil? %>
    <% @groups.each do |group| %>
      <tr>
        <td><%= link_to group.id, group_path(group) %></td>
        <td><%= link_to group.name, showMembersInGroup_path(group) %></td>
        <td><%=l group.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_group_path(group), :class => 'btn btn-mini' unless group.name.downcase.eql?"admin"%>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      group_path(group),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' unless group.name.downcase.eql?"admin"%>
        </td>
      </tr>
    <% end %>
    <% end %>
  </tbody>
</table>


  </div>
</div>

app/views/groups/new.html.erb
<%- model_class = Group -%>
	  <%= render :partial => 'navBar' %>
	  <h4><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h4>

	<%= render :partial => 'form' %>
	</div>
</div>

app/views/groups/show.html.erb
<%- model_class = Group -%>
  <%= render :partial => 'navBar' %>
  <h4><%=t '.title', :default => model_class.model_name.human.titleize %></h4>

  <dl>
	 <p id="notice"><%= notice %></p>
  </dl>

  <dl class="dl-horizontal">
    <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
    <dd><%= @group.name %></dd>
  </dl>

  <div class="form-actions">
    <%= link_to t('.back', :default => t("helpers.links.back")),
                groups_path, :class => 'btn'  %>
    <%= link_to t('.edit', :default => t("helpers.links.edit")),
                edit_group_path(@group), :class => 'btn' %>
    <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                group_path(@group),
                :method => 'delete',
                :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                :class => 'btn btn-danger' %>
  </div>
  </div>
</div>

app/views/groups/showEmailAddressesInGroup.html.erb
<%- model_class = Group -%>
  <%= render :partial => 'navBar' %>
  <h4><%= "Group: #{@group.name}" %></h4>
  <table class="table table-striped">
  <tbody>
    <% @membersInGroup.each do |member| %>
      <tr>
        <td><%= member.name %></td>
      </tr>
    <% end %>
  </tbody>
</table>
  <%= link_to t('.back', :default => t("helpers.links.back")), groups_path, :class => 'btn'  %>

  </div>
</div>

app/views/groups/showMembersInGroup.html.erb
<%- model_class = Group -%>
  <%= render :partial => 'navBar' %>
  <h4><%= "Group: #{@group.name}" %></h4>
  <table class="table table-striped">
  <thead>
      <tr>
        <th><%= model_class.human_attribute_name(:first_name) %></th>
        <th><%= model_class.human_attribute_name(:last_name) %></th>
        <th><%= model_class.human_attribute_name(:pennkey) %></th>
        <th><%= model_class.human_attribute_name(:email_address) %></th>
        <th><%= model_class.human_attribute_name(:school_id) %></th>
      </tr>
    </thead>
  <tbody>
    <% unless @membersInGroup.nil? %>
    <% @membersInGroup.each do |member| %>
      <tr>
        <td><%= member.first_name %></td>
        <td><%= member.last_name %></td>
        <td><%= member.pennkey %></td>
        <td><%= member.email_address %></td>
        <td><%= member.school.name unless member.school.nil? %></td>
      </tr>
    <% end %>
    <% end %>
  </tbody>
</table>
  <%= link_to t('.back', :default => t("helpers.links.back")), groups_path, :class => 'btn'  %>

  </div>
</div>