config/routes.rb
BlueBooks::Application.routes.draw do
  
  devise_for :members

  resources :send_documents

  get "books/index"

  get "books/new"

  get "books/create"

  get "books/destroy"

  root :to => 'members#admin_home_page'

  match 'groups/edit_members_in_group/:id' => "groups#edit_members_in_group", :as => 'edit_members_in_group'
  match 'groups/showMembersInGroup/:id' => "groups#showMembersInGroup", :as => 'showMembersInGroup'
  resources :groups

  match 'schools/show_members_in_school/:id' => "schools#show_members_in_school", :as => 'show_members_in_school'
  resources :schools
  
  put 'members/remove_member_from_group/:id' => "members#remove_member_from_group", :as => 'remove_member_from_group'
  post 'members/create_new_member' => "members#create_new_member", :as => 'create_new_member'
  match 'members/admin_home_page' => "members#admin_home_page"
  resources :members
  get 'search' => "members#search"
  
  
  resources :request_accesses
  
  get 'books/update_post_approval/:id' => 'books#update_post_approval', :as => 'update_post_approval'
  put 'books/update_post_approval/:id' => 'books#update_post_approval', :as => 'update_post_approval'
  get 'books/update/:id' => 'books#update', :as => 'update'
  match 'books/showBook_pdf/:id' => 'books#showBook_pdf', :as => 'showBook_pdf'
  resources :books, only: [:index, :new, :create, :destroy]
  get 'book_search' => "books#book_search"  
  match '/download_book/:id' => 'books#download_book', :as => 'download_book'
  
  

end

app/models/book.rb
# == Schema Information
#
# Table name: books
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  attachment :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Book < ActiveRecord::Base
  attr_accessible :attachment, :name
  mount_uploader :attachment, AttachmentUploader
  validates :name, presence: true
  validates_presence_of :name
  validates_uniqueness_of :name
  validates_presence_of :attachment
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(params[:book])
    
    if @book.save
      redirect_to books_path, notice: "The book #{@book.name} has been uploaded."
    else
      render "new"
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path, notice:  "The book #{@book.name} has been deleted."
  end
  
  def showBook_pdf
    @book = Book.find(params[:id])

    #print "******************************** #{@document.all}"
    #pdf_filename = File.join(Rails.root, "tmp/my_pdf_doc.pdf")
    #send_file(pdf_filename, :filename => "your_document.pdf", :disposition => 'inline', :type => "application/pdf")
  end

  def book_search
    @books = Book.where("name LIKE ? ", "%#{params[:book_search]}%")  
    render :template =>"books/index"
  end
  
  def download_book
    book = Book.find(params[:id])
    send_file("#{Rails.root}/public" + book.attachment_url)
  end

  def update
    @book = Book.find(params[:id]);
    book_path = "#{Rails.root}/public" + @book.attachment_url
    book_name = @book.name
    if(current_member.group and current_member.group.name.downcase.eql?"admin")
      render :template =>"books/update_post_approval"
    else
      redirect_to :controller => 'send_documents', :action => 'new', :book_path => book_path, :book_name => book_name
    end
  end

  
  def update_post_approval
    @book = Book.find(params[:id])
    @book.destroy
    @book = Book.new(params[:book])
    if @book.save
      redirect_to books_path, notice: "The book #{@book.name} has been updated."
    else
      render "new"
    end
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_navBar.html.erb
  <div class="col-xs-3">
    
  </div>
  <div class="col-xs-9">
    <div class="navbar navbar-default navbar-inverse">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          
          <div class="nav-collapse">
            <ul class="nav">
              <li><%= link_to "Home",members_admin_home_page_path %></li>
              <li><%= link_to "Books", books_path %></li>
              <li><%= link_to "Members", members_path if(current_member.group and current_member.group.name.downcase.eql?"admin")%></li>
              <li><%= link_to "Schools", schools_path if(current_member.group and current_member.group.name.downcase.eql?"admin")%></li>
              
              <li><%= link_to "Request Access", new_request_access_path if(current_member.group.nil? or !current_member.group.name.downcase.eql?"admin")%></li>
            </ul>
          </div>
        </div>
      </div>
    </div>

app/views/books/create.html.erb
<%- model_class = Book -%>
	<%= render :partial => 'navBar' %>
</div>
</div>

app/views/books/destroy.html.erb
<%- model_class = Book -%>
	<%= render :partial => 'navBar' %>
</div>
</div>

app/views/books/index.html.erb
<%- model_class = Book -%>
    <%= render :partial => 'navBar' %>
    
    <%= form_tag book_search_path, :method => 'get' do %>
    
    <table>
      <tr>
        <td>
        <h6> Search for a Book</h6>
        
      </td>
      </tr>
      <tr>
        <td><%= model_class.human_attribute_name(:name) %><br>
            <%= text_field_tag :book_search, params[:book_search]%>
        </td>        
      </tr>
      
      <tr>
        <table><tr>
        <td><%= submit_tag "Search", :name => nil, :class => "btn btn-default" %></td>
        
        <td><%= link_to "Back", members_admin_home_page_path, :class => 'btn btn-default' %></td>
        <td><%= link_to "New Book", new_book_path, class: "btn btn-primary" if(current_member.group and current_member.group.name.downcase.eql?"admin")%></td>
        </tr></table>
      </tr>
      
    </table>
    <% end %>
    <table class="table table-striped">
      <thead>
        <tr>
          <th><%= model_class.human_attribute_name(:name) %></th>
          <th>Download Link</th>
          <th><%=t '.actions', :default => t("helpers.actions") %></th>
        </tr>
      </thead>
      <tbody>
        <% unless @books.nil? %>
        <% @books.each do |book| %>
          <tr>
            <td><%= link_to book.name, showBook_pdf_path(book) %></td>
            <td><%= link_to "Download Book", download_book_path(book), :class => "btn btn-default" %></td>
            <td><%= link_to "Update", update_path(book), :class => 'btn btn-mini' %>
            <%= link_to "Delete",  book, method: :delete, class: "btn btn-danger btn-mini", confirm: "Are you sure that you wish to delete #{book.name}?" if(current_member.group and current_member.group.name.downcase.eql?"admin")%></td>
          </tr>
        <% end %>
        <% end %>
      </tbody>
    </table>
</div>
</div>

app/views/books/new.html.erb
<%- model_class = Book -%>
    <%= render :partial => 'navBar' %>
    <% if !@book.errors.empty? %>
      <div class="alert alert-error">
        <ul>
          <% @book.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="well">
      <%= form_for @book, html: { multipart: true } do |f| %>
        <%= f.label :name %>
        <%= f.text_field :name %>
        <%= f.label :attachment %>
        <%= f.file_field :attachment %>
        <%= f.submit "Save", class: "btn btn-primary" %>
      <% end %>
    </div>
</div>
</div>

app/views/books/showBook_pdf.html.erb
<%- model_class = Book -%>
  <%= render :partial => 'navBar' %>
  <h4><%= @book.name %></h4>
  <% file_name = @book.attachment  %>
  <div style="vertical-align:top">
	  <%= link_to "Download", download_book_path(@book), :class => "btn btn-default"%>
	  <%= link_to t('.back', :default => t("helpers.links.back")), books_path, :class => 'btn' %>
  </div>
  <table>
      <tr>
        <td>
          <iframe src=<%= asset_path(file_name) %> width="900" height="500" style="border: none;"> </iframe>
        </td>
        
      </tr>
  </table>

</div>
</div>

app/views/books/update_post_approval.html.erb
<%- model_class = Book -%>
    <%= render :partial => 'navBar' %>
    <% if !@book.errors.empty? %>
      <div class="alert alert-error">
        <ul>
          <% @book.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="well">
      <%= form_for @book, html: { multipart: true }, :url => {:action =>'update_post_approval'} do |f| %>
        <%= f.label :name %>
        <%= f.text_field :name, :input_html => {:value => "#{@book.name}"} %>
        <%= f.label :attachment %>
        <%= f.file_field :attachment %><br/>
        <%= f.submit "Save", class: "btn btn-primary" %>
        <%= link_to "Cancel", books_path, :class => 'btn' %>
      <% end %>

    </div>
</div>
</div>