config/routes.rb
BlueBooks::Application.routes.draw do
  
  devise_for :members

  resources :send_documents

  get "books/index"

  get "books/new"

  get "books/create"

  get "books/destroy"

  root :to => 'members#admin_home_page'

  match 'groups/edit_members_in_group/:id' => "groups#edit_members_in_group", :as => 'edit_members_in_group'
  match 'groups/showMembersInGroup/:id' => "groups#showMembersInGroup", :as => 'showMembersInGroup'
  resources :groups

  match 'schools/show_members_in_school/:id' => "schools#show_members_in_school", :as => 'show_members_in_school'
  resources :schools
  
  put 'members/remove_member_from_group/:id' => "members#remove_member_from_group", :as => 'remove_member_from_group'
  post 'members/create_new_member' => "members#create_new_member", :as => 'create_new_member'
  match 'members/admin_home_page' => "members#admin_home_page"
  resources :members
  get 'search' => "members#search"
  
  
  resources :request_accesses
  
  get 'books/update_post_approval/:id' => 'books#update_post_approval', :as => 'update_post_approval'
  put 'books/update_post_approval/:id' => 'books#update_post_approval', :as => 'update_post_approval'
  get 'books/update/:id' => 'books#update', :as => 'update'
  match 'books/showBook_pdf/:id' => 'books#showBook_pdf', :as => 'showBook_pdf'
  resources :books, only: [:index, :new, :create, :destroy]
  get 'book_search' => "books#book_search"  
  match '/download_book/:id' => 'books#download_book', :as => 'download_book'
  
  

end

app/models/school.rb
# == Schema Information
#
# Table name: schools
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class School < ActiveRecord::Base
  attr_accessible :name
  has_many :members
  
  validates_uniqueness_of :name, message: 'already exists'
  validates :name, presence: {message: ' cannot be empty'}
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  # GET /schools
  # GET /schools.json
  def index
    @schools = School.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @schools }
    end
  end

  # GET /schools/1
  # GET /schools/1.json
  def show
    @school = School.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @school }
    end
  end

  # GET /schools/new
  # GET /schools/new.json
  def new
    @school = School.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @school }
    end
  end

  # GET /schools/1/edit
  def edit
    @school = School.find(params[:id])
  end

  # POST /schools
  # POST /schools.json
  def create
    @school = School.new(params[:school])

    respond_to do |format|
      if @school.save
        format.html { redirect_to @school, notice: 'School was successfully created.' }
        format.json { render json: @school, status: :created, location: @school }
      else
        format.html { render action: "new" }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /schools/1
  # PUT /schools/1.json
  def update
    @school = School.find(params[:id])

    respond_to do |format|
      if @school.update_attributes(params[:school])
        format.html { redirect_to @school, notice: 'School was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schools/1
  # DELETE /schools/1.json
  def destroy
    @school = School.find(params[:id])
    @school.destroy

    respond_to do |format|
      format.html { redirect_to schools_url }
      format.json { head :no_content }
    end
  end

  def show_members_in_school
    @school = School.find(params[:id])

    @membersInSchool = @school.members
    
  end
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/views/schools/_form.html.erb
<% if @school.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@school.errors.count, "error") %> prohibited this school from being saved:</h2>

      <ul>
      <% @school.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<%= form_for @school, :html => { :class => 'form-horizontal' } do |f| %>
  
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                schools_path, :class => 'btn' %>
  </div>
<% end %>

app/views/schools/_navBar.html.erb
  <div class="col-xs-3">
    
  </div>
  <div class="col-xs-9">
    <div class="navbar navbar-default navbar-inverse">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          
          <div class="nav-collapse">
            <ul class="nav">
              <li><%= link_to "Home",members_admin_home_page_path %></li>
              <li><%= link_to "Books", books_path %></li>
              <li><%= link_to "Members", members_path if(current_member.group and current_member.group.name.downcase.eql?"admin")%></li>
              <li><%= link_to "Schools", schools_path if(current_member.group and current_member.group.name.downcase.eql?"admin")%></li>
              
              <li><%= link_to "Request Access", new_request_access_path if(current_member.group.nil? or !current_member.group.name.downcase.eql?"admin")%></li>
            </ul>
          </div>
        </div>
      </div>
    </div>

app/views/schools/edit.html.erb
<%- model_class = School -%>
	<%= render :partial => 'navBar' %>
	<h4><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h4>
	<%= render :partial => 'form' %>
</div>
</div>

app/views/schools/index.html.erb
<%- model_class = School -%>
    <%= render :partial => 'navBar' %>
    <h4><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h4>
    <%= link_to t('.new', :default => t("helpers.links.new")),new_school_path,:class => 'btn btn-primary' %>
    <%= link_to "Back", members_admin_home_page_path, :class => 'btn btn-default' %>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% unless @schools.nil? %>
    <% @schools.each do |school| %>
      <tr>
        <td><%= link_to school.id, school_path(school) %></td>
        <td><%= link_to school.name, show_members_in_school_path(school) %></td>
        <td><%=l school.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_school_path(school), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      school_path(school),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
    <% end %>
  </tbody>
</table>


  </div>
</div>

app/views/schools/new.html.erb
<%- model_class = School -%>
	<%= render :partial => 'navBar' %>
	<h4><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>

<%= render :partial => 'form' %>
	</div>
</div>

app/views/schools/show.html.erb
<%- model_class = School -%>
  <%= render :partial => 'navBar' %>

  <h4><%=t '.title', :default => model_class.model_name.human.titleize %></h4>
<dl>
  <p id="notice"><%= notice %></p>
</dl>
<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @school.name %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              schools_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_school_path(@school), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              school_path(@school),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>
</div>
</div>

app/views/schools/show_members_in_school.html.erb
<%- model_class = School -%>
  <%= render :partial => 'navBar' %>
  <h4><%= "School: #{@school.name}" %></h4>
  <table class="table table-striped">
    <thead>
        <tr>
          <th><%= model_class.human_attribute_name(:first_name) %></th>
          <th><%= model_class.human_attribute_name(:last_name) %></th>
          <th><%= model_class.human_attribute_name(:pennkey) %></th>
          <th><%= model_class.human_attribute_name(:email_address) %></th>
          <th><%= model_class.human_attribute_name(:group_id) %></th>
        </tr>
      </thead>
  <tbody>
    <% unless @membersInSchool.nil? %>
    <% @membersInSchool.each do |member| %>
      <tr>
        <td><%= member.first_name %></td>
        <td><%= member.last_name %></td>
        <td><%= member.pennkey %></td>
        <td><%= member.email_address %></td>
        <td><%= member.group.name unless member.group.nil? %></td>
      </tr>
    <% end %>
    <% end %>
  </tbody>
</table>
  <%= link_to t('.back', :default => t("helpers.links.back")), schools_path, :class => 'btn'  %>

  </div>
</div>