config/routes.rb
BlueBooks::Application.routes.draw do
  
  devise_for :members

  resources :send_documents

  get "books/index"

  get "books/new"

  get "books/create"

  get "books/destroy"

  root :to => 'members#admin_home_page'

  match 'groups/edit_members_in_group/:id' => "groups#edit_members_in_group", :as => 'edit_members_in_group'
  match 'groups/showMembersInGroup/:id' => "groups#showMembersInGroup", :as => 'showMembersInGroup'
  resources :groups

  match 'schools/show_members_in_school/:id' => "schools#show_members_in_school", :as => 'show_members_in_school'
  resources :schools
  
  put 'members/remove_member_from_group/:id' => "members#remove_member_from_group", :as => 'remove_member_from_group'
  post 'members/create_new_member' => "members#create_new_member", :as => 'create_new_member'
  match 'members/admin_home_page' => "members#admin_home_page"
  resources :members
  get 'search' => "members#search"
  
  
  resources :request_accesses
  
  get 'books/update_post_approval/:id' => 'books#update_post_approval', :as => 'update_post_approval'
  put 'books/update_post_approval/:id' => 'books#update_post_approval', :as => 'update_post_approval'
  get 'books/update/:id' => 'books#update', :as => 'update'
  match 'books/showBook_pdf/:id' => 'books#showBook_pdf', :as => 'showBook_pdf'
  resources :books, only: [:index, :new, :create, :destroy]
  get 'book_search' => "books#book_search"  
  match '/download_book/:id' => 'books#download_book', :as => 'download_book'
  
  

end

app/models/member.rb
# == Schema Information
#
# Table name: members
#
#  id                     :integer          not null, primary key
#  pennkey                :string(255)
#  first_name             :string(255)
#  last_name              :string(255)
#  email_address          :string(255)
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  school_id              :integer
#  group_id               :integer
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0)
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#
# Indexes
#
#  index_members_on_email                 (email) UNIQUE
#  index_members_on_reset_password_token  (reset_password_token) UNIQUE
#

class Member < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  attr_accessible :email_address, :first_name, :last_name, :pennkey, :school_id, :group_id, 
  :email, :password, :password_confirmation, :sign_in_count, :current_sign_in_at, :last_sign_in_at, 
  :remember_me, :current_sign_in_ip, :last_sign_in_ip 

  belongs_to :school
  belongs_to :group
  

  validates_uniqueness_of :email_address, message: 'already exists' 
  validates_uniqueness_of :pennkey, message: 'already exists'
  validates :email_address, :email => true, presence: {message: ' cannot be empty'}
  validates :first_name, presence: {message: ' cannot be empty'}
  validates :last_name, presence: {message: ' cannot be empty'}
  validates :pennkey, presence: {message: ' cannot be empty'}
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  # GET /members
  # GET /members.json
  def index
    @members = Member.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @members }
    end
  end

  # GET /members/1
  # GET /members/1.json
  def show
    @member = Member.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @member }
    end
  end

  # GET /members/new
  # GET /members/new.json
  def new
    @member = Member.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @member }
    end
  end

  # GET /members/1/edit
  def edit
    @member = Member.find(params[:id])
  end

  # POST /members
  # POST /members.json
  # def create
  #   p "**********************"
  #   @member = Member.new(params[:member])


  #   respond_to do |format|
  #     if @member.save
  #       format.html { redirect_to @member, notice: 'Member was successfully created.' }
  #       format.json { render json: @member, status: :created, location: @member }
  #     else
  #       format.html { render action: "new" }
  #       format.json { render json: @member.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # PUT /members/1
  # PUT /members/1.json
  def update
    @member = Member.find(params[:id])

    respond_to do |format|
      if @member.update_attributes(params[:member])
        format.html { redirect_to @member, notice: 'Member was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1
  # DELETE /members/1.json
  def destroy
    @member = Member.find(params[:id])
    @member.destroy

    respond_to do |format|
      format.html { redirect_to members_url }
      format.json { head :no_content }
    end
  end

  def search
    @members = Member.where("first_name LIKE ? AND last_name LIKE ? AND pennkey LIKE ? AND email_address LIKE ?", "%#{params[:fnsearch]}%","%#{params[:lnsearch]}%", "%#{params[:pksearch]}%", "%#{params[:easearch]}%")  
    render :template =>"members/index"
  end

  def admin_home_page

  end

  # Create a new member - after devise
  def create_new_member
    
    member_params = params[:member]
    
    member_params["password"] = "123123123"
    member_params["password_confirmation"] = "123123123"
    member_params["email"] = member_params["email_address"]
    @member = Member.new(member_params)
    
    respond_to do |format|
      if @member.save
        format.html { redirect_to @member, notice: 'Member was successfully created.' }
        format.json { render json: @member, status: :created, location: @member }
      else
        format.html { render action: "new" }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  def remove_member_from_group
    @member = Member.find(params[:id])
    @old_group = @member.group
    if @member.update_attributes(:group_id => nil)
       redirect_to edit_members_in_group_path(@old_group) 
      else
        format.json { render json: @member.errors, status: :unprocessable_entity }
        redirect_to edit_members_in_group_path(@old_group)
      end
    
  end
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/members/_form.html.erb
<% if @member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@member.errors.count, "error") %> prohibited this member from being saved:</h2>

      <ul>
      <% @member.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<%= form_for @member, :html => { :class => 'form-horizontal' }, :url => create_new_member_path(@member) do |f| %>
  

  <div class="control-group">
    <%= f.label :pennkey, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :pennkey, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :first_name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :first_name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :last_name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :last_name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :email_address, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :email_address, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :school_id, :class => 'control-label' %>
    <div class="controls">
      <%= collection_select :member, :school_id, School.all, :id, :name  %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :group_id, :class => 'control-label' %>
    <div class="controls">
      <%= collection_select :member, :group_id, Group.all, :id, :name  %>
    </div>
  </div>
  
  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                members_admin_home_page_path, :class => 'btn' %>
  </div>
<% end %>

app/views/members/_form_create.html.erb
<% if @member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@member.errors.count, "error") %> prohibited this member from being saved:</h2>

      <ul>
      <% @member.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<%= form_for @member, :html => { :class => 'form-horizontal' }, :url => create_new_member_path(@member)  do |f| %>
  

  <div class="control-group">
    <%= f.label :pennkey, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :pennkey, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :first_name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :first_name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :last_name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :last_name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :email_address, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :email_address, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :school_id, :class => 'control-label' %>
    <div class="controls">
      <%= collection_select :member, :school_id, School.all, :id, :name  %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :group_id, :class => 'control-label' %>
    <div class="controls">
      <%= collection_select :member, :group_id, Group.all, :id, :name  %>
    </div>
  </div>
  
  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                members_admin_home_page_path, :class => 'btn' %>
  </div>
<% end %>

app/views/members/_navBar.html.erb
  <div class="col-xs-3">
    
  </div>
  <div class="col-xs-9">
    <div class="navbar navbar-default navbar-inverse">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          
          <div class="nav-collapse">
            <ul class="nav">
              <li><%= link_to "Home",members_admin_home_page_path %></li>
              <li><%= link_to "Books", books_path %></li>
              <li><%= link_to "Members", members_path if(current_member.group and current_member.group.name.downcase.eql?"admin")%></li>
              <li><%= link_to "Schools", schools_path if(current_member.group and current_member.group.name.downcase.eql?"admin")%></li>
              
              <li><%= link_to "Request Access", new_request_access_path if(current_member.group.nil? or !current_member.group.name.downcase.eql?"admin")%></li>
              
            </ul>
          </div>
        </div>
      </div>
    </div>

app/views/members/admin_home_page.html.erb
<%- model_class = Member -%>
	<%= render :partial => 'navBar' %>
    <div style="background-color:#eeeeee;padding:20px">
    <%= form_tag search_path, :method => 'get' do %>
    
    <ul>
      <% if(current_member.group and current_member.group.name.downcase.eql?"admin") %>
      <li><h6><%= link_to("Search for a member", members_path) %></h6></li>
      <li><h6><%= link_to("Create a new member", new_member_path) %></h6></li>
      <li><h6><%= link_to("Manage Schools", schools_path)%></h6></li>
      <li><h6><%= link_to("Manage Groups", groups_path) %></h6></li>
      <% end %>

      <% if(current_member.group.nil? or !current_member.group.name.downcase.eql?"admin") %>
      <li><h6><%= link_to("Request Access", new_request_access_path) %></h6></li>
      <% end %>
      <li><h6><%= link_to("Books", books_path) %></h6></li>
      
    </ul>
    
    <% end %>
    </div>


  </div>
</div>

app/views/members/edit.html.erb
<%- model_class = Member -%>
		<%= render :partial => 'navBar' %>
	    <h4><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h4>
		<%= render :partial => 'form' %>

	</div>
</div>

app/views/members/home.html.erb
<%- model_class = Member -%>
	<%= render :partial => 'navBar' %>

    <%= form_tag search_path, :method => 'get' do %>
    
    <ul>
      <li><h6><%= link_to("Search for a member", members_path) %></h6></li>
      <li><h6><%= link_to("Create a new member", new_member_path) %></h6></li>
      <li><h6><%= link_to("Add a new school", new_school_path)%></h6></li>
      <li><h6><%= link_to("Manage Groups", groups_path) %></h6></li>
      
    </ul>
    
    <% end %>
    


  </div>
</div>

app/views/members/index.html.erb
<%- model_class = Member -%>
    <%= render :partial => 'navBar' %>
    
    <%= form_tag search_path, :method => 'get' do %>
    
    <table>
      <tr>
        <td>
        <h6> Search for an existing member</h6>
        
      </td>
      </tr>
      <tr>
        <td style="padding-right:10px"><%= model_class.human_attribute_name(:first_name) %><br>
            <%= text_field_tag :fnsearch, params[:fnsearch]%>
        </td>
        <td style="padding-right:10px"><%= model_class.human_attribute_name(:last_name) %><br>
            <%= text_field_tag :lnsearch, params[:lnsearch]%>
        </td>
        
      
        <td style="padding-right:10px"><%= model_class.human_attribute_name(:pennkey) %><br>
            <%= text_field_tag :pksearch, params[:pksearch]%>
        </td>    
        <td style="padding-right:10px"><%= model_class.human_attribute_name(:email_address) %><br>
            <%= text_field_tag :easearch, params[:easearch]%>
        </td>
      </tr>
      <tr>
        <td>
          <%= submit_tag "Search", :name => nil, :class => "btn btn-default" %>
          <%= link_to t('.back', :default => t("helpers.links.back")), members_admin_home_page_path, :class => 'btn' %>
        </td>
      </tr>
      
    </table>

    
    <% end %>
    
    <table class="table table-striped">
      <thead>
        <tr>
          <th><%= model_class.human_attribute_name(:id) %></th>
          <th><%= model_class.human_attribute_name(:pennkey) %></th>
          <th><%= model_class.human_attribute_name(:first_name) %></th>
          <th><%= model_class.human_attribute_name(:last_name) %></th>
          <th><%= model_class.human_attribute_name(:email_address) %></th>
          <th><%= model_class.human_attribute_name(:school_id) %></th>
          <th><%= model_class.human_attribute_name(:group_id) %></th>
          <th><%=t '.actions', :default => t("helpers.actions") %></th>
        </tr>
      </thead>
      <tbody>
        
        <% unless @members.nil? %>
         <% @members.each do |member| %>
          <tr>
            <td><%= link_to member.id, member_path(member) %></td>
            <td><%= member.pennkey %></td>
            <td><%= member.first_name %></td>
            <td><%= member.last_name %></td>
            <td><%= member.email_address %></td>
            <td><%= member.school.name unless member.school.nil? %></td>
            <td><%= member.group.name unless member.group.nil? %></td>
            <td>
              <%= link_to t('.edit', :default => t("helpers.links.edit")),
                          edit_member_path(member), :class => 'btn btn-mini' %>
              <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                          member_path(member),
                          :method => :delete,
                          :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                          :class => 'btn btn-mini btn-danger' %>
            </td>
          </tr>
        <% end %>
        <% end %>
      </tbody>
    </table>

 
  </div>  
  </div>
</div>

app/views/members/new.html.erb
<%- model_class = Member -%>
	<%= render :partial => 'navBar' %>

	<h4><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h4>

	<%= render :partial => 'form_create' %>

	
	</div>
</div>

app/views/members/show.html.erb
<%- model_class = Member -%>
  <%= render :partial => 'navBar' %>
  <h4><%=t '.title', :default => model_class.model_name.human.titleize %></h4>
<dl>
  <p id="notice"><%= notice %></p>
</dl>
<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:pennkey) %>:</strong></dt>
  <dd><%= @member.pennkey %></dd>
  <dt><strong><%= model_class.human_attribute_name(:first_name) %>:</strong></dt>
  <dd><%= @member.first_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:last_name) %>:</strong></dt>
  <dd><%= @member.last_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:email_address) %>:</strong></dt>
  <dd><%= @member.email_address %></dd>
  <dt><strong><%= model_class.human_attribute_name(:school_id) %>:</strong></dt>
  <dd><%= @member.school.name %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              members_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_member_path(@member), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              member_path(@member),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

</div>
</div>